### ISSUE TITLE
RFC: Dimension Field Tagging

### ISSUE THREAD

**Issue by garyluoex** [yahoo/fili#135]
RFC: Dimension Field Tagging
======================================

- Feature Name: Dimension Field Tags
- Start Date: 2017-01-11
- RFC PR: TBD WIP
- Original RFC: [Primary Dimension Field Expansion](https://github.com/yahoo/fili/issues/93)

Summary
-------
[summary]: #summary

Fili `Dimension`s having only one core field, the "key" field, has gotten us a long way, but it has become obvious that all `Dimension`s have more core fields than that, which serve other common use-cases. We propose to extend the `DimensionField` model to allow fields to be tagged with user defined `Tag`s, and to surface these `Tag`s through the dimension endpoint so that clients can make use of them.

Motivation
----------
[motivation]: #motivation

As Fili usage has expanded, additional use-cases have surfaced around `Dimension`s, particularly when it comes to core fields of a `Dimension`. For example, programmatic clients, like web UIs, often want more information about the fields of a `Dimension` in order to provide a good user experience. This includes things like "Which fields are unique?", "Which fields are the default search fields?", "Which fields are alternate identifiers?", and "Which fields should I use when displaying a `DimensionRow` in various contexts?" Some of these use cases are already handled, or are mostly handled. For example, `Dimension` already has the concepts of a "key" field and of "default dimension fields", but we don't fully solve for those use cases because those concepts are not surfaced in the `Dimension` resource.

Method
---------------
[design]: #method

In order to make `DimensionField`s more expressive, we'd like to propose the addition of Dimension Field Tagging into Fili. A `Tag` is essentially a string defined by the user which implicitly carries certain meanings that are agreed upon the webservice and the API clients. In the case of a UI client, `Tag`s such as "display" and "description" can be defined in Fili application and attached to specific `DimensionField`(s) to indicate that the corresponding `DimensionField`(s) should be used as the name displayed to the user and the detailed description for the current `Dimension` respectively. To preserve the concept of core "key" field in Fili, a default `Tag` named "primaryKey" will be provided to the users so that the first field tagged with the "primaryKey" `Tag` will be treated as the core "key" field in Fili (if not tagged, the default behavior now is first field specified is treated as the core "key" field). Note that it should be possible and reasonable that `Tag`s can be assigned to multiple `Dimension`s if needed and that a single `DimensionField` can have several `Tag`s.

Example of current dimension endpoint response:
```json
{
  "category": "SpecialDimensions",
  "name": "dim1",
  "longName": "Dimension 1",
  "description": "Dimension 1 is a special dimension",
  "fields": [
    {
      "name": "id",
      "description": "Dimension ID"
    }, {
      "name": "desc",
      "description": "Dimension Description"
    }, {
      "name": "localId",
      "description": "Local ID of the dimension"
    }
  ]
}
```

Example of the expected dimensions endpoint response after Dimension Field Tagging implementation: 
```json
{
  "category": "SpecialDimensions",
  "name": "dim1",
  "longName": "Dimension 1",
  "description": "Dimension 1 is a special dimension",
  "fields": [
    {
      "name": "id",
      "description": "Dimension ID",
      "tags": ["primaryKey"]
    }, {
      "name": "desc",
      "description": "Dimension Description",
      "tags": ["description"]
    }, {
      "name": "localId",
      "description": "Local ID of the dimension"
    }
  ]
}
```

Current Design
---------------
[design]: #current-design

To realize `Dimension Field Tagging` in Fili, we'd like to propose the following changes to the Fili code base:

1. Add the concept of `DimensionFieldTag`

    This requires introducing a new model (interface) that represents a `DimensionField`'s `Tag` in Fili. The `Tag` model should be simple at first, containing only the string representation of the `Tag` along with its type. Additional properties and behaviors can be added or extended later on to make the `Tag` model more expressive. In addition, users can also add their own model of `Tag` by extending our `Tag` interface.

2. Add the a new`DimensionField` interface, `TaggedDimensionField`

    User configures `DimensionField`s for `Dimension`s in their Fili application, by adding the `TaggedDimensionField` interface, we are allowing users to have full control of the `Tag`(s) associated to `DimensionField`s. In the case that the user does not care about the `tags` attribute, the default `DimensionField` interface can be used.

3. Expose `tags` attribute through dimension endpoint
   
    After the above two changes are made, the dimensions end point should return `Dimension` objests as json where the user can access the attribute `tags` as a list in the `fields` attribute of `Dimension`. This way API clients will be able to retrieve tagging information and therefore utilize tagged fields accordingly. In particular, the expectation is that this information can help drive programmatic clients like UI applications. This information may also be useful for API "power users", by giving them some insight into additional semantics of `DimensionField`s, and could allow for richer experiences like default filtering, where the field isn't specified, on columns other than the "key" column.

Drawbacks
---------
[drawbacks]: #drawbacks

We can see a few drawbacks to this change:

1. Larger dimension endpoint response size
Mitigation: Config serializer to ignore the `tags` field if it is empty

2. Potentially more to config
Mitigation: Provide default behavior that does not break backward compatibility

3. More complexity
Mitigation: The complexity is likely already there, Fili just doesn't capture it or expose it
Mitigation: Can solve through documentation
Mitigation: Can hide the complexity via default fields or config defaults, so only those who need it or go looking for it have to deal with the complexity

3. Might need to deprecate core `key` field concept
Mitigation: For the better

4. API change
Mitigation: Adding, not changing or removing, so is backwards compatible

Alternatives
------------
[alternatives]: #alternatives

Alt design:
1. Hard code the meaning of fields into their names

What if not?
1. Clients need to hard-code the info, or get it from some other source

Unresolved Questions
--------------------
[unresolved]: #unresolved-questions

- Improvements on the design?
- Additional features in the future for `Tag`?

**Comment by cdeszaq** [comment]
Just to clarify, how is this proposal expecting the Dimension response to change? Right now, it looks something like this:

```json
{
  "category": "SpecialDimensions",
  "name": "dim1",
  "longName": "Dimension 1",
  "description": "Dimension 1 is a special dimension",
  "fields": [
    {
      "name": "id",
      "description": "Dimension ID"
    }, {
      "name": "desc",
      "description": "Dimension Description"
    }, {
      "name": "localId",
      "description": "Local ID of the dimension"
    }
  ],
  "values": "https://data.example.com:4443/v1/dimensions/dim1/values",
  "cardinality": 4524,
  "tables": [
    {
      "category": "general",
      "name": "company",
      "longName": "Company",
      "granularity": "day",
      "uri": "https://data.example.com:4443/v1/tables/company/day"
    }, {
      "category": "general",
      "name": "company",
      "longName": "Company",
      "granularity": "week",
      "uri": "https://data.example.com:4443/v1/tables/company/week"
    }
  ]
}
```

With this proposal, would the `fields` section change to be something like this:

```json
"fields": [
  {
    "name": "id",
    "description": "Dimension ID",
    "tags": ["primaryKey"]
  }, {
    "name": "desc",
    "description": "Dimension Description",
    "tags": ["description"]
  }, {
    "name": "localId",
    "description": "Local ID of the dimension"
  }
]
```

Also, is the plan to have some set of "built in" tags that all user agents can understand and be aware of? I would think "primaryKey", since it's already a concept, would be a built-in tag, but I didn't see any mention of that in the proposal.

Other than those few questions, this looks pretty good to me.

**Comment by garyluoex** [comment]
Updated the RFC based on rick's comment.

**Comment by garyluoex** [comment]
Close for now since it turns out this does not make much sense to fit in fili-core.
