### ISSUE TITLE
GroovyTestUtils::compareErrorPayload does not handle nested queries

### ISSUE THREAD

**Issue by cdeszaq** [yahoo/fili#146]
For single-layer queries, it finds the context and rips out the UUID pieces so that they compare cleanly. For queries with more than 1 layer, however, it doesn't clean context blocks for deeper layers, making the method essentially useless.

To fix, we need to make the cleaning process much smarter, so that it dives down into nested queries (when present) and cleans them as well, rolling up the values the right way.

/cc
@will-lauer (impacted by this bug)
@archolewa (implemented the original solution)

**Comment by cdeszaq** [comment]
@archolewa did this get fixed?

**Comment by archolewa** [comment]
Yes. https://github.com/yahoo/fili/pull/147
