### ISSUE TITLE
DruidWebService should return a Future for druid queries

### ISSUE THREAD

**Issue by kevinhinterlong** [yahoo/fili#216]
The AsyncDruidWebServiceImpl gives a callback for when it finishes, but it can't be forced to finish with the current interface methods 
```java
void postDruidQuery(...);
void getJsonObject(...);
```
so maybe refactor it to something along the lines of 
```java
Future<Response> postDruidQuery(...);
Future<Response> getJsonObject(...);
```

**Comment by cdeszaq** [comment]
Fixed.
