### ISSUE TITLE
Change Exception type in MetricUnionCompositeTable while verifying grain

### ISSUE THREAD

**Issue by QubitPi** [yahoo/fili#240]
![screen shot 2017-04-13 at 11 29 32 am](https://cloud.githubusercontent.com/assets/16126939/25014238/7fd53cce-203c-11e7-9f62-8e71da606be0.png)

@garyluoex suggests changing `IllegalArgumentException` to runtime exception.

**Comment by garyluoex** [comment]
No really needed, closing it.
