### ISSUE TITLE
DateTimeUtils is insufficiently tested

### ISSUE THREAD

**Issue by cdeszaq** [yahoo/fili#298]
Some of the methods are unused and could be removed. Perhaps instead this could be pulled into it's own module?

**Comment by QubitPi** [comment]
I'm working on it.

**Comment by QubitPi** [comment]
I've added tests for all methods, because down-stream projects might use all of them.

**Comment by QubitPi** [comment]
Addressed by https://github.com/yahoo/fili/pull/595
