### ISSUE TITLE
Move Contributing details from README.md to CONTRIBUTING.md

### ISSUE THREAD

**Issue by kevinhinterlong** [yahoo/fili#303]
The [CONTRIBUTING](https://github.com/yahoo/fili/blob/master/CONTRIBUTING.md) file is pretty empty and the information takes up a lot of space in the [README](https://github.com/yahoo/fili/blob/master/README.md)

**Comment by cdeszaq** [comment]
This is a great idea. Just be sure to leave a pointer in the primary README file as advertisment.
