### ISSUE TITLE
ApiJobStore Interface should have Pagination baked into it's methods

### ISSUE THREAD

**Issue by archolewa** [yahoo/fili#36]
Just like SearchProvider supports Paginated results, we should update methods in ApiJobStore that return multiple JobRows to support pagination.

Note that one issue with using the Pagination approach is that it breaks the reactive interface that the `ApiJobStore` is using. Instead of being able to send back an `Observable`, and then apply streamy operations to it, we would instead have to return a `Pagination` object. 

So to address this issue, we either need to give up on ReactiveX, keep pagination external to the interface, add yet another pagination object that contains an `Observable`, or rework the `Pagination` objects to properly support ReactiveX (and get rid of the awkward `AllPagesPagination` and `SinglePagePagination` objects).

**Comment by QubitPi** [comment]
Addressed by https://github.com/yahoo/fili/pull/23
