### ISSUE TITLE
Make Slices endpoint URL building safe instead of stringy

### ISSUE THREAD

**Issue by cdeszaq** [yahoo/fili#373]
We can build links using the URL Builder (or however the Dimension endpoint does it), which is much safer that doing it with string manipulations.

**Comment by kevinhinterlong** [comment]
I think this is already in place using the below method
```java
public static String getSliceDetailUrl(String slice, UriInfo uriInfo) { // line 229
    return uriInfo.getBaseUriBuilder()
            .path(SlicesServlet.class)
            .path(SlicesServlet.class, "getSliceBySliceName")
            .build(slice)
            .toASCIIString();
} // SlicesServlet.java
```

@QubitPi or @michael-mclawhorn Can you double check this? If you agree then this should be closed

**Comment by michael-mclawhorn** [comment]
This was already resolved
