### ISSUE TITLE
Make test strings groovier

### ISSUE THREAD

**Issue by cdeszaq** [yahoo/fili#388]
Some of our tests (particularly the *QuerySpec) make heavy use of the concatenation operator when constructing strings. This approach is not necessary in the face of Groovy string interpolations, and they are significantly less clear.

They should be converted into proper [Groovy string interpolations](http://docs.groovy-lang.org/latest/html/documentation/index.html#_string_interpolation).

For example, convert this:

```groovy
vars.filter = vars.filter ? ((' "filter": ').replaceAll(/\s/, "") + vars.filter + ',') : ""
vars.context = vars.context ? (('{"queryId":"dummy100",').replaceAll(/\s/, "") + vars.context + '}') : '{"queryId":"dummy100"}'
vars.sort = vars.sort ? ((' "sort": "').replaceAll(/\s/, "") + vars.sort + '",') : ""
```

into this:

```groovy
vars.filter = vars.filter ? /"filter": $vars.filter,/ : ""
vars.context = vars.context = vars.context ? /{"queryId":"dummy100",$vars.context}/ : /{"queryId": "dummy100"}/
vars.sort = vars.sort ? /"sort":"$vars.sort",/ : ""
```

<sub>Note the use of `/` to allow for string interpolation without having to escape double-quotes.</sub>

**Comment by QubitPi** [comment]
Addressed by https://github.com/yahoo/fili/issues/406
