### ISSUE TITLE
Slices endpoint gives api name instead of druid name

### ISSUE THREAD

**Issue by cdeszaq** [yahoo/fili#394]
Since it's main purpose in life is to surface debug info about segment info pulled in from Druid, it should stay in Physical land primarily, and _include_ (not replace) logical info (ie. dimension API names)

**Comment by QubitPi** [comment]
@cdeszaq I can work on this. Could you add little more description on how to implement this?

**Comment by cdeszaq** [comment]
Since the slices endpoints are tied to the physical table, they should be showing the physical names for the dimensions, not the API names of the dimensions. Right now, the endpoints are showing the API names, which isn't as useful. So, find the place where the Slices output is using API names, and make them use physical names from the tables instead.

**Comment by QubitPi** [comment]
@cdeszaq Are you talking about changing names for dimensions for names for table?

**Comment by kevinhinterlong** [comment]
@QubitPi If you're not working on it I think I'd like to take this one
