### ISSUE TITLE
Possible doc update

### ISSUE THREAD

**Issue by QubitPi** [yahoo/fili#402]
Is this still true at this moment? https://github.com/yahoo/fili/blame/master/docs/end-user-api.md#L211 - "Only `in` and `notin` are supported at the moment"

**Comment by michael-mclawhorn** [comment]
yes?

**Comment by QubitPi** [comment]
@michael-mclawhorn I updated link

**Comment by kevinhinterlong** [comment]
It looks like { `in`, `notin`, `eq`, `startswith`, `contains` } are supported by default from 
```java
public enum FilterOperation {
    in,
    notin,
    startswith,
    contains,
    eq
} // FilterOperation.java
```
but `startswith` and `contains` can be turned off using the `data_filter_substring_operations_enabled` feature flag

```java
if (!BardFeatureFlag.DATA_FILTER_SUBSTRING_OPERATIONS.isOn()) { // line 1079
    FilterOperation filterOperation = newFilter.getOperation();
    if (filterOperation.equals(FilterOperation.startswith)
            || filterOperation.equals(FilterOperation.contains)
            ) {
        throw new BadApiRequestException(
                ErrorMessageFormat.FILTER_SUBSTRING_OPERATIONS_DISABLED.format()
        );
    }
} // DataApiRequest.java 
```

So this needs an update
