### ISSUE TITLE
Make functional tests not lock on the same files

### ISSUE THREAD

**Issue by kevinhinterlong** [yahoo/fili#462]
The `LuceneSearchProvider` requires a lot of file locks and tests using it operate on the same the same `lucene_index_path` for reading/writing. Since all these tests operate in the same directory, it prevents multiple of these tests running at the same time and provides a potential place for test interference.

The end goal being would be to make tests able to run in parallel, whether or not that actually happens by default will probably depend on how well travis handles it.

**Comment by QubitPi** [comment]
Addressed
