### ISSUE TITLE
Maven build warnings: tasks parameter is deprecated

### ISSUE THREAD

**Issue by kevinhinterlong** [yahoo/fili#467]
In `fili-system-config/pom.xml`, the `maven-antrun-plugin` uses the deprecated `tasks` parameter to generate test resources. We should move to using `target` instead.

```
[INFO] --- maven-antrun-plugin:1.8:run (default) @ fili-system-config ---
[WARNING] Parameter tasks is deprecated, use target instead
```

**Comment by kevinhinterlong** [comment]
@dejan2609 Would you like to take this one?

**Comment by dejan2609** [comment]
Sure @kevinhinterlong, I'll take it.
