### ISSUE TITLE
Update Response Format contract to use headers

### ISSUE THREAD

**Issue by michael-mclawhorn** [yahoo/fili#494]
Response Format should follow the following rules:
responseFormat URI parameter and Accept header are evaluated.

URI parameter has precedence over Accept header.
* Acceptable defaults will map make application/json synonymous with json default format.
* application/vnd.api+json will be synonymous with json-api format.
* text/csv will be synonymous with the csv format.

If no responseFormat is specified in the URI then the server may choose any of the Accept types presented and no promise is made as to which will be preferred if multiple legal mappings exist.

**Comment by tarrantzhang** [comment]
I think I can take this one.

**Comment by QubitPi** [comment]
Addressed by https://github.com/yahoo/fili/pull/520
