### ISSUE TITLE
Filter variables and methods in DataApiRequest are confusing

### ISSUE THREAD

**Issue by tarrantzhang** [yahoo/fili#497]
ApiFilter is call `filters` while Druid filter is call `filter` in `DataApiRequest`. This is very confusing for people trying to understand the code. In my opinion, they should be changed to `apiFilter` and `druidFilter` respectively. And also their getters.

**Comment by michael-mclawhorn** [comment]
There's a reason that API filters are considered plural while Druid filters are singular. Because API filters are treated as a list (or a list grouped into a map by dimension) while the Druid filters are a tree with a leaf node as the reference variable.

**Comment by QubitPi** [comment]
Addressed by https://github.com/yahoo/fili/pull/507
