### ISSUE TITLE
Support dimension metadata to indicate storage strategy 

### ISSUE THREAD

**Issue by jkusa** [yahoo/fili#548]
In order to allow clients to be notified if a dimension's values are browsable and searchable we need a way to indicate the storage strategy. 

A new dimension metadata attribute can be added at the top level called `storageStrategy` with values:

- `loaded`  --> indicates that values are loaded into fili and are browsable and searchable
- `none` --> indicates that values are NOT available
- etc

**Comment by QubitPi** [comment]
[Addressed](https://github.com/yahoo/fili/pull/558)
