### ISSUE TITLE
Add serializer/deserializer for dimension, metric configuration

### ISSUE THREAD

**Issue by michael-mclawhorn** [yahoo/fili#6]
Create serialization proxy classes able to serialize and deserialize dimension configuration.  Ideally, support human-friendly editable versions which also support tooling for partial generations.

**Comment by cdeszaq** [comment]
Is this a dupe of #73?

**Comment by michael-mclawhorn** [comment]
Closed as part of Luthier
https://github.com/yahoo/fili/tree/master/luthier
