### ISSUE TITLE
Partial intervals which have been deserialized may be more generic than SimplifiedIntervalList and fail downstream.

### ISSUE THREAD

**Issue by QubitPi** [yahoo/fili#657]
Some downstream projects generated partial intervals as `ArrayList`, which cannot be cased to `SimplifiedIntervalList` in places like [`getPartialIntervalsWithDefault`](https://github.com/yahoo/fili/blob/master/fili-core/src/main/java/com/yahoo/bard/webservice/web/handlers/PartialDataRequestHandler.java#L113). The result is a casting exception which crashes downstream applications.

Although https://github.com/yahoo/fili/pull/658 is a reasonable alternative to cleaning up all the source of the type precision loss. This does raise the question of whether this needs to be an SIL in all these interfaces, but this is good enough for now.

**Edit - This problem happens in `getVolatileIntervalsWithDefault` as well which is fixed in https://github.com/yahoo/fili/pull/678**

**Comment by michael-mclawhorn** [comment]
This is particularly being detecting in HttpResponseMaker after async triggered serialization and deserialization.

**Comment by QubitPi** [comment]
Addressed by https://github.com/yahoo/fili/pull/658
