### ISSUE TITLE
Query splitting seems to break "all" grain when multiple disjoint intervals specified

### ISSUE THREAD

**Issue by cdeszaq** [yahoo/fili#72]
The query generated and shown with `format=debug` looks correct, and it returns a single time bucket when run directly against Druid, but when the Fili response comes back, you get 2 time buckets for the "all" query, which should have been 1. 

This is also borne out in the logs, which show that a query split is happening, even though "all" grain queries should _never_ be split.

**Comment by michael-mclawhorn** [comment]
The conceptual error is here:

https://github.com/yahoo/fili/blob/master/fili-core/src/main/java/com/yahoo/bard/webservice/web/handlers/SplitQueryRequestHandler.java#L66

The expectedIntervals is flattening the concept of a bucket with an interval.  Under any TimeGrain, intervals must be non disjoint at the resolution of buckets.  But under the all granularity disjoint intervals can share the same bucket.  

Either there needs to be a bailout special case for 'all' here, or the splitter has be be layered so it can handle buckets which are not expressible in a single interval.

**Comment by cdeszaq** [comment]
Fixed by #75
