### ISSUE TITLE
File based configuration for Dimensions and Tables would be fantastic to have

### ISSUE THREAD

**Issue by cdeszaq** [yahoo/fili#73]
Dimensions and Tables are often fairly straight-forward, and super common in terms of what their configuration looks like in most cases. It would be good to have a file-based config so that it's easier to maintain and could possibly be generated.

**Comment by cdeszaq** [comment]
Is this a dupe of #6?

**Comment by michael-mclawhorn** [comment]
Yes

**Comment by michael-mclawhorn** [comment]
https://github.com/yahoo/fili/tree/master/luthier
