### ISSUE TITLE
Customize Logging Format

### ISSUE THREAD

**Issue by archolewa** [yahoo/fili#74]
Currently, Fili exports the log information accumulated by `RequestLog` as a JSON. However, different clients may wish to use different formats for that information. Therefore, we should add an injection point that allows customers to provide their own output format.

Here's a brief sketch of how we could do that:

a. Add a LogFormat interface with a single method: `format` that takes in the `RequestLog` and returns a formatted `String` to be logged.
b. Add a configuration parameter that takes the fully-qualified classname of the formatter.
c. Provide a default implementation that formats the `RequestLog` into JSON.
c. Update `RequestLog` to pull in the `LogFormat` implementation at initialization time. Modify `RequestLog::export` to  pass the log information through that formatter.

**Comment by cdeszaq** [comment]
This looks good to me. 👍

**Comment by archolewa** [comment]
This has been implemented.
