### ISSUE TITLE
Making Custom Sketch operations possible in PostAggreations

### ISSUE THREAD

**Issue by deepakb91** [yahoo/fili#740]
1. The `asSketchEstimate(SketchAggregation candidate)` of `ThetaSketchFieldConverter` class currently takes `SketchAggregation` as the parameter and returns `SketchAggregation` as a `ThetaSketchEstimatePostAggregation `. 
2. Rather than taking `SketchAggregation` as a parameter, we can make two versions of `asSketchEstimate` with one taking `Aggregation` as a parameter and the other taking `PostAggregation` as a parameter so that only the metrics which are part of `Aggregation` are marked as field access whereas the ones which are part of `PostAggregation` are not. 
3. This will help in doing some custom sketch operations in the PostAggregations.

**Comment by QubitPi** [comment]
Resolved by https://github.com/yahoo/fili/pull/741
