### ISSUE TITLE
Change BasePhysicalTable to defer getAvailableIntervals() to availability

### ISSUE THREAD

**Issue by efronbs** [yahoo/fili#744]
Base Physical table currently defers `getAvailableIntervals(constraint)` and `getAllAvailableIntervals()` to its availability, but does not override `getAvailableIntervals()` from the `PhysicalTable` interface. The default implementation in `PhysicalTable` is to union the availability of all columns on the table. This behavior is probably not correct for `BasePhysicalTable`. The correct behavior is likely to defer this to the availability, just like the other two availability methods.

**Comment by QubitPi** [comment]
Resolved by https://github.com/yahoo/fili/pull/743
