### ISSUE TITLE
Change `BaseCompositePhysicalTable` to a concrete class

### ISSUE THREAD

**Issue by efronbs** [yahoo/fili#746]
Currently `BaseCompositePhysicalTable` implements simple composite table behavior. However, it is an abstract class so using it requires extending it. `BaseCompositePhysicalTable` can become a concrete class, so you can use create simple composite physical tables without having to implement your own version of it.

**Comment by QubitPi** [comment]
Resolved by https://github.com/yahoo/fili/pull/745
