### ISSUE TITLE
Support Filtering Segment Availability from Availability Service

### ISSUE THREAD

**Issue by archolewa** [yahoo/fili#77]
We are planning in the near future to pull availability off of Physical Tables, and instead make it a separate service tentatively keyed on the physical table and the query. 

When doing so, it would be great if we also provide first-class support for filtering the availability segments returned by the service based on some predicate. 

More concretely, I would like to be able to truncate a physical table's availability to the past 90 days, regardless of what the backing Druid datasource says.

**Comment by cdeszaq** [comment]
Update: I _think_ this is being addressed / handled with #226 or perhaps #207. In the end, filtering the availability should be done within the PhysicalTable, which is also what is currently doing the "filter the availability down to the relevant columns".

Once this gets landed and stabilized, I'll circle back and update this issue with the outcome.

**Comment by cdeszaq** [comment]
@archolewa This should now be fixed, since the PR to address it just merged. If you find that _not_ to be the case, please re-open this 😄
