### ISSUE TITLE
ConjuctionDruidFilterBuilder uses way too many static methods

### ISSUE THREAD

**Issue by archolewa** [yahoo/fili#792]
The ConjunctionDruidFilterBuilder has a whole bunch of protected static helper
methods. This makes that builder *very* rigid, and a pain to customize, 
especially if a customer needs to do just a little bit of tweaking (like adding
some additional logging). Therefore, those should be made instance methods.

In my opinion (though I'm biased) we should make things extensible unless we 
have a *very* good reason not to, and static methods are not extensible. Static
methods in particular should be reserved for standalone functions that don't
belong on a class. Utility functions basically.

**Comment by michael-mclawhorn** [comment]
Fixed
