### ISSUE TITLE
Several endpoints logs the entire response 

### ISSUE THREAD

**Issue by zmz0305** [yahoo/fili#852]
Several endpoints (Slice, Table, Metrics, etc.) logs the entire response which makes the log not readable and potentially causing performance issues.

**Comment by garyluoex** [comment]
Hello, 

This employee can no longer access email on this account.  Your email will not be forwarded.

If you have a sales inquiry, please contact sales@yahoo-inc.com

If you require assistance with a legal matter, please contact legal-notices@yahoo-inc.com

Thank you!

**Comment by zmz0305** [comment]
Related PR https://github.com/yahoo/fili/pull/853
