### ISSUE TITLE
Overwriting keyvalue store's key

### ISSUE THREAD

**Issue by sriram-viswanathan** [yahoo/fili#89]
Reference: https://github.com/yahoo/fili/blob/master/fili-core/src/main/java/com/yahoo/bard/webservice/util/DimensionStoreKeyUtils.java#L49

By lower-casing the value part, there could be issues where both `FOO` and `foo` will end up having same key which causes the druid query to always return results for only `foo` and miss `FOO`

**Comment by archolewa** [comment]
Looks like this issue has been resolved by #90.
