### ISSUE TITLE
remove internal URLs references from the docs

### ISSUE THREAD

**Issue by gyehuda** [yahoo/fili#9]
Michael, 
Please remove the references to internal URLs (e.g. jira.corp and git.corp) https://github.com/yahoo/fili/blob/80f00a6c25cc23269e3a1440b081d512f1e5001d/docs/built-in-makers.md
Thanks

**Comment by michael-mclawhorn** [comment]
We are about to drop a completely new, more thoroughly reviewed, sanitized image of fili to github.com.

**Comment by archolewa** [comment]
Should we be closing this issue? I'm pretty sure we've addressed it.

**Comment by cdeszaq** [comment]
Fixed
